### ISSUE TITLE
Treehouse courses to be completed

### ISSUE THREAD

**Issue by RyanFisha** [RyanFisha/RyanFisha#1]
## TODO

*Courses left to be completed*

* [ ] CSS layout basics
* [ ] JavaScript Loops, Arrays, & Objects
* [ ] JavaScript and the Dom
* [ ] CSS Flexbox Layout
* [ ] Jquery Basics
* [ ] Responsive Layouts

🎉  😸
